-- GENERATED by scripts/gen-apply-all.mjs — DO NOT EDIT BY HAND.
-- Edit the component supabase/*.sql and re-run the generator.
-- Paste into a fresh Postgres (with the pgvector extension) for the full Spectre
-- schema; safe to re-run. Embeddings are vector(768) for the default
-- nomic-embed-text embedder; if EMBED_PROVIDER=openai, set EMBED_DIM=1536 and resize.

-- Quiet the idempotency scaffolding: DROP ... IF EXISTS on a fresh database
-- emits a "does not exist, skipping" NOTICE per object, which reads like the
-- apply skipped things. Session-local; plain WARNING+ still shows.
SET client_min_messages = warning;

-- ============================================================
-- schema.sql
-- ============================================================
-- Spectre Database Schema
-- Run this in your Supabase SQL Editor

-- Enable pgvector for memory embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- APP CONFIG (key-value for session PIN, preferences, etc.)
-- ============================================================
CREATE TABLE IF NOT EXISTS app_config (
  key           TEXT PRIMARY KEY,
  value         JSONB NOT NULL,
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- PROJECTS (group threads + plugins)
-- ============================================================
CREATE TABLE IF NOT EXISTS projects (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  description   TEXT,
  color         TEXT DEFAULT '#6366f1',
  active        BOOLEAN DEFAULT TRUE,
  metadata      JSONB DEFAULT '{}',
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- THREADS
-- ============================================================
CREATE TABLE IF NOT EXISTS threads (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title         TEXT,
  project_id    UUID REFERENCES projects(id) ON DELETE SET NULL,
  pinned        BOOLEAN DEFAULT FALSE,
  archived      BOOLEAN DEFAULT FALSE,
  model_hint    TEXT,
  reasoning_effort TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_threads_updated ON threads(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_threads_project ON threads(project_id);

-- ============================================================
-- MESSAGES
-- ============================================================
CREATE TABLE IF NOT EXISTS messages (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id     UUID NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  role          TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool')),
  content       TEXT,
  model_used    TEXT,
  tool_calls    JSONB,
  tool_call_id  TEXT,
  attachments   JSONB DEFAULT '[]',
  token_count   INTEGER,
  latency_ms    INTEGER,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(thread_id, created_at);

-- ============================================================
-- MEMORY (long-term facts)
-- ============================================================
CREATE TABLE IF NOT EXISTS memory (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content       TEXT NOT NULL,
  category      TEXT DEFAULT 'general',
  source_msg_id UUID REFERENCES messages(id) ON DELETE SET NULL,
  -- Must equal EMBED_DIM (default 768 = nomic-embed-text). The memory-embeddings
  -- migration also drop+re-adds this at 768; keep the base consistent so applying
  -- schema.sql alone isn't a silent recall-breaker for self-hosters.
  embedding     vector(768),
  importance    SMALLINT DEFAULT 5 CHECK (importance BETWEEN 1 AND 10),
  last_accessed TIMESTAMPTZ DEFAULT NOW(),
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_memory_embedding ON memory USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS idx_memory_category ON memory(category);

-- ============================================================
-- PLUGINS (MCP servers + OpenAPI imports)
-- ============================================================
CREATE TABLE IF NOT EXISTS plugins (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  type          TEXT NOT NULL CHECK (type IN ('mcp_stdio', 'mcp_sse', 'openapi')),
  enabled       BOOLEAN DEFAULT TRUE,
  config        JSONB NOT NULL DEFAULT '{}',
  project_id    UUID REFERENCES projects(id) ON DELETE SET NULL,
  tools_cache   JSONB,
  last_synced   TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- TOOL EXECUTION LOG
-- ============================================================
CREATE TABLE IF NOT EXISTS tool_executions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id    UUID REFERENCES messages(id) ON DELETE SET NULL,
  plugin_id     UUID REFERENCES plugins(id) ON DELETE SET NULL,
  tool_name     TEXT NOT NULL,
  input         JSONB,
  output        JSONB,
  status        TEXT CHECK (status IN ('success', 'error', 'timeout')),
  duration_ms   INTEGER,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- VOICE SESSIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS voice_sessions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id     UUID REFERENCES threads(id) ON DELETE SET NULL,
  started_at    TIMESTAMPTZ DEFAULT NOW(),
  ended_at      TIMESTAMPTZ,
  transcript    JSONB DEFAULT '[]',
  duration_sec  INTEGER
);

-- ============================================================
-- FILE UPLOADS metadata
-- ============================================================
CREATE TABLE IF NOT EXISTS uploads (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  storage_path  TEXT NOT NULL,
  original_name TEXT NOT NULL,
  mime_type     TEXT NOT NULL,
  size_bytes    BIGINT,
  thread_id     UUID REFERENCES threads(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- WORKSHOP TASKS (Spectre self-improvement via Claude Code)
-- ============================================================
CREATE TABLE IF NOT EXISTS workshop_tasks (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title         TEXT NOT NULL,
  description   TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'running', 'completed', 'failed', 'cancelled')),
  branch_name   TEXT,
  pr_url        TEXT,
  pr_number     INTEGER,
  claude_output TEXT DEFAULT '',
  error         TEXT,
  started_at    TIMESTAMPTZ,
  completed_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_workshop_tasks_status ON workshop_tasks(status);
CREATE INDEX IF NOT EXISTS idx_workshop_tasks_created ON workshop_tasks(created_at DESC);

-- ============================================================
-- Auto-update updated_at on threads
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS threads_updated_at ON threads;
CREATE TRIGGER threads_updated_at
  BEFORE UPDATE ON threads
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- Update thread.updated_at when a message is inserted
-- ============================================================
CREATE OR REPLACE FUNCTION touch_thread_on_message()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE threads SET updated_at = NOW() WHERE id = NEW.thread_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS messages_touch_thread ON messages;
CREATE TRIGGER messages_touch_thread
  AFTER INSERT ON messages
  FOR EACH ROW
  EXECUTE FUNCTION touch_thread_on_message();

-- ============================================================
-- durable-chat.sql
-- ============================================================
-- Durable chat: runs are queued in the DB, executed by the chat-runner, and
-- streamed to the UI via Realtime — so a generation survives the UI connection
-- dropping (close the laptop, Spectre keeps going; reattach anywhere). Rerunnable.

-- Per-message generation status. Existing rows are complete -> 'done'.
-- New flow: assistant placeholder 'queued' -> 'running' -> 'done'|'error'|'cancelled'.
alter table messages add column if not exists status text not null default 'done';

-- Runner lease columns (mirrors the locked_at/locked_by pattern on scheduled_jobs).
-- The chat-runner sets both atomically with the queued->running claim, heartbeats
-- locked_at every 60 s during execution, and the boot orphan-recovery only reclaims
-- rows whose lease is null or older than STALE_MS (20 min default) — leaving live
-- in-flight runs on sibling/surviving runners untouched.
alter table messages add column if not exists locked_at timestamptz;
alter table messages add column if not exists locked_by text;

create index if not exists messages_status_idx
  on messages (status)
  where status in ('queued', 'running', 'cancelled');

-- Realtime so the UI viewer sees the assistant row fill in live and the runner
-- can pick up work. replica identity full -> UPDATE payloads include content.
alter table messages replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table messages;
  end if;
end $$;

-- ============================================================
-- channels.sql
-- ============================================================
-- Messaging channels: inbound webhook -> durable Spectre turn -> outbound delivery.
-- A channel chat reuses ONE thread per (channel, sender) so context persists; the
-- thread carries metadata.channel = { type, chat_id } so the outbound worker knows
-- where to send the reply. Default-deny: only allowed senders are acted on.

create table if not exists channel_accounts (
  id uuid primary key default gen_random_uuid(),
  channel text not null,
  sender_id text not null,
  thread_id uuid references threads(id) on delete set null,
  allowed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (channel, sender_id)
);

-- Outbound dedupe marker: an assistant reply on a channel-bound thread is sent
-- exactly once, then stamped delivered_at. Durable (survives worker restarts) —
-- the chat-runner's orphan recovery shows why in-process sent-sets are unsafe.
alter table messages add column if not exists delivered_at timestamptz;

-- The outbound worker scans for undelivered, finished assistant replies.
create index if not exists idx_messages_undelivered
  on messages (thread_id)
  where delivered_at is null and status = 'done' and role = 'assistant';

-- Service role full access; anon none (this is the inbound sender allowlist —
-- anon write access would let anyone allowlist themselves).
alter table channel_accounts enable row level security;

drop policy if exists "service role full access" on channel_accounts;
DROP POLICY IF EXISTS "service role full access" ON channel_accounts;
CREATE POLICY "service role full access" ON channel_accounts
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ============================================================
-- memory-embeddings.sql
-- ============================================================
-- Semantic memory: local-embedder vector search.
-- The default embedder is local Ollama nomic-embed-text (768-dim); the original
-- column was sized for OpenAI (1536). Resize + add a cosine-similarity RPC.
-- Safe to rerun. If you switch to OpenAI embeddings, change 768 -> 1536 here
-- and re-embed.

-- Also removes the old ivfflat index on installs that predate the exact-KNN
-- switch (see note below).
drop index if exists idx_memory_embedding;

-- Existing rows have no embedding yet, so dropping/re-adding is lossless.
alter table memory drop column if exists embedding;
alter table memory ADD COLUMN IF NOT EXISTS embedding vector(768);

-- NOTE: deliberately NO ivfflat/approximate index (same rule as
-- generated_media/pdf_chunks). ivfflat with a fixed `lists` count silently
-- returns 0 rows on small tables (a single-probe query lands in an empty
-- list), which killed recall on fresh installs. Memory stays small after the
-- nightly dedup/decay, so an exact KNN sort is sub-millisecond AND always
-- correct. If memory ever grows past ~100k rows, add an HNSW index (no
-- empty-probe hole) — not ivfflat.

-- Top-K cosine similarity over memories (optionally filtered by category).
create or replace function match_memory(
  query_embedding vector(768),
  match_count int default 8,
  filter_category text default null
)
returns table (
  id uuid,
  content text,
  category text,
  importance smallint,
  similarity float
)
language sql stable
as $$
  select m.id, m.content, m.category, m.importance,
         1 - (m.embedding <=> query_embedding) as similarity
  from memory m
  where m.embedding is not null
    and (filter_category is null or m.category = filter_category)
  order by m.embedding <=> query_embedding
  limit match_count;
$$;

-- ============================================================
-- messages-embeddings.sql
-- ============================================================
-- Cross-thread message recall: semantic search over raw chat messages so Spectre
-- can answer "what did we decide/discuss in that OTHER conversation last week".
--
-- Mirrors the memory-embeddings pattern exactly: a local-embedder vector(768)
-- column (Ollama nomic-embed-text) + a top-K cosine RPC. Messages are embedded
-- lazily in the background (the nightly dream backfill), NEVER on the chat write
-- path, so sends stay fast. Safe to rerun. If you switch to OpenAI embeddings,
-- change 768 -> 1536 here and re-embed.

alter table messages add column if not exists embedding vector(768);

-- NOTE: deliberately NO ivfflat/approximate index (same rule as
-- generated_media/pdf_chunks). ivfflat with a fixed `lists` count silently
-- returns 0 rows on small tables (a single-probe query lands in an empty
-- list), which killed cross-thread recall on fresh installs. match_messages
-- does an exact `order by embedding <=> query` instead — correct at every
-- size, fast at single-user scale. If messages grows past ~100k embedded
-- rows, add an HNSW index (no empty-probe hole) — not ivfflat. The drop also
-- migrates installs that predate this switch.
drop index if exists idx_messages_embedding;

-- Speeds up the backfill's "rows still missing a vector" scan.
create index if not exists idx_messages_embedding_pending
  on messages (created_at)
  where embedding is null;

-- Top-K message snippets by cosine similarity (cross-thread). Only real
-- conversation turns (user/assistant) are searchable; system/tool rows and
-- unembedded rows are excluded. The caller filters by threshold + excludes the
-- current thread.
create or replace function match_messages(
  query_embedding vector(768),
  match_count int default 8
)
returns table (
  id uuid,
  thread_id uuid,
  role text,
  content text,
  created_at timestamptz,
  similarity float
)
language sql stable
as $$
  select m.id, m.thread_id, m.role, m.content, m.created_at,
         1 - (m.embedding <=> query_embedding) as similarity
  from messages m
  where m.embedding is not null
    and m.role in ('user', 'assistant')
  order by m.embedding <=> query_embedding
  limit match_count;
$$;

-- ============================================================
-- ingest.sql
-- ============================================================
-- Ingest events — signals modules push INTO the core (the active/bidirectional
-- direction). A module posts an observation; the core stores it and can react
-- (remember / notify / hand it to Spectre for a proactive turn). Safe to rerun.
create table if not exists ingest_events (
  id          uuid primary key default gen_random_uuid(),
  module      text not null,
  kind        text not null default 'event',
  summary     text,
  data        jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists ingest_events_created_idx on ingest_events (created_at desc);
create index if not exists ingest_events_module_idx on ingest_events (module);

-- Service role full access; anon none (signal payloads are personal, and anon
-- inserts could enqueue proactive turns).
alter table ingest_events enable row level security;

drop policy if exists "service role full access" on ingest_events;
DROP POLICY IF EXISTS "service role full access" ON ingest_events;
CREATE POLICY "service role full access" ON ingest_events
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ============================================================
-- modules.sql
-- ============================================================
-- Module installs — the registry's persisted half.
--
-- `/api/modules` returns the built-in modules merged over the rows here, so an
-- installed module shows up in the blob without a redeploy. A row's `manifest`
-- is the full jerome.module.json v2 doc (uiMode + ui + permissions intact); the
-- route reads it raw (the trust boundary is install-time validation, not read).
--
-- `ui_mode` is denormalized out of the manifest for cheap filtering. Disabled
-- rows are skipped by the route (status filter). Safe to rerun (idempotent).
create table if not exists module_installs (
  id          uuid primary key default gen_random_uuid(),
  module_id   text not null unique,
  version     text not null,
  ui_mode     text not null default 'data' check (ui_mode in ('native', 'data', 'code')),
  manifest    jsonb not null,
  status      text not null default 'installed' check (status in ('installed', 'disabled')),
  created_at  timestamptz not null default now()
);

create index if not exists module_installs_status_idx on module_installs (status);

-- Service role full access; anon none (the registry is internal).
alter table module_installs enable row level security;

drop policy if exists "service role full access" on module_installs;
DROP POLICY IF EXISTS "service role full access" ON module_installs;
CREATE POLICY "service role full access" ON module_installs
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ============================================================
-- model_backends.sql
-- ============================================================
-- Model backends — user-taught, modular model backends (api / cli-server / cli-command).
--
-- The unified registry's persisted half. The core dual-writes here AND to
-- <dataDir>/backends/backends.json (the mcp-broker reads that file to register
-- cli-dispatch tools — it has no DB access). `spec` is the full ModelBackend v1
-- doc; the loader validates it with zod on read.
--
-- Secrets (provider api keys) are NEVER stored here — they are forwarded to the
-- LiteLLM gateway, which encrypts them in its own store (store_model_in_db).
-- `status` mirrors spec.enabled for cheap filtering. Safe to rerun (idempotent).
create table if not exists model_backends (
  id          text primary key,
  kind        text not null check (kind in ('api', 'cli-server', 'cli-command')),
  label       text not null,
  status      text not null default 'enabled' check (status in ('enabled', 'disabled')),
  spec        jsonb not null,
  created_at  timestamptz not null default now()
);

create index if not exists model_backends_status_idx on model_backends (status);

-- Service role full access; anon none (the registry is internal).
alter table model_backends enable row level security;

drop policy if exists "service role full access" on model_backends;
DROP POLICY IF EXISTS "service role full access" ON model_backends;
CREATE POLICY "service role full access" ON model_backends
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ============================================================
-- module-data.sql
-- ============================================================
-- Per-module data store — the tables a module's declarative backend writes to
-- via the capability shim (src/lib/modules/store.ts). EVERY query is hard-
-- filtered by module_id, so a module only ever touches its OWN namespace.
-- Two shapes:
--   module_kv   — namespaced key→jsonb   (get / set / list / del)
--   module_rows — namespaced append log  (append / rows)
-- Service-role-only (RLS), mirroring notes.sql. Safe to rerun (idempotent).

create table if not exists module_kv (
  module_id   text not null,
  key         text not null,
  value       jsonb,
  updated_at  timestamptz not null default now(),
  primary key (module_id, key)
);

create table if not exists module_rows (
  id          uuid primary key default gen_random_uuid(),
  module_id   text not null,
  collection  text not null,
  doc         jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists module_kv_module_idx on module_kv (module_id);
create index if not exists module_rows_module_collection_idx
  on module_rows (module_id, collection, created_at desc);

-- Service role full access; anon none (per-module data is internal).
alter table module_kv enable row level security;
alter table module_rows enable row level security;

drop policy if exists "service role full access" on module_kv;
DROP POLICY IF EXISTS "service role full access" ON module_kv;
CREATE POLICY "service role full access" ON module_kv
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists "service role full access" on module_rows;
DROP POLICY IF EXISTS "service role full access" ON module_rows;
CREATE POLICY "service role full access" ON module_rows
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ============================================================
-- monitor_events.sql
-- ============================================================
-- Monitor events — written by the spectre-monitor agent every 5 minutes.
-- Run this in your Supabase SQL Editor after schema.sql.

CREATE TABLE IF NOT EXISTS monitor_events (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  severity      TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
  component     TEXT NOT NULL,
  description   TEXT NOT NULL,
  action_taken  TEXT,
  action_result TEXT,
  raw_vitals    JSONB,
  analysis      JSONB
);

CREATE INDEX IF NOT EXISTS idx_monitor_events_created  ON monitor_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_monitor_events_severity ON monitor_events (severity);

-- Service role full access; anon none (events carry error details/vitals, and
-- anon writes could inject fake "issues" into Spectre's per-turn prompt block).
alter table monitor_events enable row level security;

drop policy if exists "service role full access" on monitor_events;
DROP POLICY IF EXISTS "service role full access" ON monitor_events;
CREATE POLICY "service role full access" ON monitor_events
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- Auto-prune: keep only 7 days of events to avoid unbounded growth.
-- Run this as a cron job in Supabase, or add to a pg_cron extension schedule.
-- DELETE FROM monitor_events WHERE created_at < NOW() - INTERVAL '7 days';

-- ============================================================
-- notes.sql
-- ============================================================
-- Spectre notes + todos store.
-- Run once in Supabase SQL Editor. Safe to rerun.
--
-- Two kinds in the same table:
--   kind='note' → free-form thought/idea the user dictated. Optional `pinned`.
--   kind='todo' → structured task. Optional `deadline`, `priority`,
--                 `done` checkbox.
--
-- Distinct from `memory` which holds long-term facts about the user /
-- projects. Spectre saves notes via note.add / todo.add and retrieves
-- with note.list / note.search.

create table if not exists notes (
  id                uuid primary key default gen_random_uuid(),
  kind              text not null default 'note' check (kind in ('note', 'todo')),
  content           text not null,
  pinned            boolean not null default false,
  -- todo-specific (null for kind='note')
  deadline          timestamptz,
  priority          text check (priority in ('low', 'medium', 'high', 'urgent')),
  done              boolean not null default false,
  done_at           timestamptz,
  -- provenance
  source_msg_id     uuid references messages(id) on delete set null,
  source_thread_id  uuid references threads(id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists notes_kind_idx on notes (kind);
create index if not exists notes_created_at_idx on notes (created_at desc);
create index if not exists notes_pinned_idx on notes (pinned) where pinned = true;
create index if not exists notes_todo_open_idx on notes (deadline asc nulls last) where kind = 'todo' and done = false;

-- Service role full access; anon none (notes are personal).
alter table notes enable row level security;

drop policy if exists "service role full access" on notes;
DROP POLICY IF EXISTS "service role full access" ON notes;
CREATE POLICY "service role full access" ON notes
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ============================================================
-- pdf_library.sql
-- ============================================================
-- ============================================================
-- PDF LIBRARY — documents + RAG chunks + reading-session threads
-- ============================================================
-- Idempotent migration. Run via Supabase SQL editor (or psql).
-- Adds:
--   * pdf_documents — uploaded PDF metadata + intake status
--   * pdf_chunks    — page-aware text chunks with pgvector embeddings
--   * threads.metadata column — used to mark a thread as a "reading
--                               session" so /api/threads/[id]/messages
--                               can scope RAG retrieval to its pdf_ids
--   * match_pdf_chunks RPC for top-k cosine retrieval
-- ============================================================

CREATE TABLE IF NOT EXISTS pdf_documents (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  filename      TEXT NOT NULL,
  title         TEXT,
  summary       TEXT,
  category      TEXT,
  tags          TEXT[] DEFAULT '{}',
  status        TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','processing','ready','failed')),
  file_path     TEXT NOT NULL,
  file_size     BIGINT,
  page_count    INTEGER,
  error         TEXT,
  uploaded_at   TIMESTAMPTZ DEFAULT NOW(),
  processed_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_pdf_documents_status   ON pdf_documents(status);
CREATE INDEX IF NOT EXISTS idx_pdf_documents_uploaded ON pdf_documents(uploaded_at DESC);

CREATE TABLE IF NOT EXISTS pdf_chunks (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  doc_id        UUID NOT NULL REFERENCES pdf_documents(id) ON DELETE CASCADE,
  chunk_index   INTEGER NOT NULL,
  page_start    INTEGER NOT NULL,
  page_end      INTEGER NOT NULL,
  text          TEXT NOT NULL,
  token_count   INTEGER,
  embedding     vector(768),
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pdf_chunks_doc       ON pdf_chunks(doc_id);
-- NOTE: no ivfflat/approximate vector index on purpose. match_pdf_chunks ALWAYS
-- filters `WHERE doc_id = ANY(doc_ids)` (a reading session = a handful of PDFs),
-- so the planner filters on idx_pdf_chunks_doc first and does an EXACT cosine
-- sort over that small subset — sub-ms and always correct. An ivfflat index here
-- is actively harmful: a single-probe scan lands in a list that may hold none of
-- the attached docs' chunks, returning 0 hits so RAG silently never fires (the
-- same pgvector small-table/post-filter trap that bit generated_media).

-- threads.metadata: marks a thread as kind='pdf-session' and stores
-- the open-set of pdf_ids it's bound to. Used by the chat route to
-- scope RAG retrieval. Defaults to '{}' so existing threads keep
-- working unchanged.
ALTER TABLE threads ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS idx_threads_metadata_kind ON threads ((metadata->>'kind'));

-- Top-k retrieval scoped to the open-set of PDFs.
CREATE OR REPLACE FUNCTION match_pdf_chunks(
  query_embedding vector(768),
  doc_ids UUID[],
  match_count INT
) RETURNS TABLE (
  id UUID,
  doc_id UUID,
  page_start INT,
  page_end INT,
  text TEXT,
  similarity FLOAT
) LANGUAGE sql STABLE AS $$
  SELECT
    id,
    doc_id,
    page_start,
    page_end,
    text,
    1 - (embedding <=> query_embedding) AS similarity
  FROM pdf_chunks
  WHERE doc_id = ANY(doc_ids) AND embedding IS NOT NULL
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;

-- ============================================================
-- generated-media.sql
-- ============================================================
-- Generated media library: screenshots (+ other generated images) with metadata
-- and an embedding, so (a) the agent can RESURFACE past media by description and
-- (b) the UI (Memory tab / Library) can browse it. The image bytes live on the
-- /generated rail (files); this table is the index + recall layer.

create table if not exists generated_media (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,                 -- /generated/<name> filename
  url         text not null,                        -- /generated/<name>
  kind        text not null default 'screenshot',   -- screenshot | image
  caption     text,                                 -- human/agent description (embedded)
  thread_id   uuid references threads(id) on delete set null,
  embedding   vector(768),                          -- nomic-embed-text (EMBED_DIM)
  created_at  timestamptz not null default now()
);

create index if not exists idx_generated_media_created on generated_media (created_at desc);
-- NOTE: deliberately NO ivfflat/approximate index. A media library is small
-- (hundreds–thousands of rows), where an exact KNN sort is sub-millisecond AND
-- always correct. ivfflat with a fixed `lists` count silently drops recall on
-- small tables (a single-probe query lands in an empty list -> 0 rows), which is
-- exactly wrong for "resurface this image". match_generated_media does an exact
-- `order by embedding <=> query` instead.

-- Top-K cosine recall over captions (rows without an embedding are skipped).
create or replace function match_generated_media(
  query_embedding vector(768),
  match_count int default 12
)
returns table (
  id uuid,
  name text,
  url text,
  kind text,
  caption text,
  created_at timestamptz,
  similarity float
)
language sql stable
as $$
  select g.id, g.name, g.url, g.kind, g.caption, g.created_at,
         1 - (g.embedding <=> query_embedding) as similarity
  from generated_media g
  where g.embedding is not null
  order by g.embedding <=> query_embedding
  limit match_count;
$$;

-- ============================================================
-- push_subscriptions.sql
-- ============================================================
-- Web Push subscription store.
-- Run once in the Supabase SQL editor (Dashboard → SQL Editor).

create table if not exists push_subscriptions (
  id         uuid primary key default gen_random_uuid(),
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  created_at timestamptz not null default now()
);

-- Service role has full access; anon has none (subscriptions are internal).
alter table push_subscriptions enable row level security;

DROP POLICY IF EXISTS "service role full access" ON push_subscriptions;
CREATE POLICY "service role full access" ON push_subscriptions
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ============================================================
-- connected_accounts.sql
-- ============================================================
-- Connected mail/calendar accounts (Microsoft + Google), multi-account.
-- Replaces the single app_config 'ms_graph_tokens' blob: one row per account so a
-- user can connect several Microsoft and/or Google accounts and Spectre reads
-- calendars (and later email, on-demand) across all of them.
-- Run once in the Supabase SQL editor (Dashboard → SQL Editor).

create table if not exists connected_accounts (
  id            uuid primary key default gen_random_uuid(),
  provider      text not null,               -- 'microsoft' | 'google'
  account_email text not null,               -- identity within a provider
  account_name  text,
  access_token  text not null,
  refresh_token text not null,
  expires_at    timestamptz,                 -- access-token expiry (ISO)
  scopes        text,                         -- granted scopes, space-separated
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (provider, account_email)           -- re-connecting an account updates it
);

create index if not exists connected_accounts_provider_idx
  on connected_accounts (provider);

-- Service role has full access; anon/authenticated have none (tokens are internal).
alter table connected_accounts enable row level security;

DROP POLICY IF EXISTS "service role full access" ON connected_accounts;
CREATE POLICY "service role full access" ON connected_accounts
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ============================================================
-- scheduled_jobs.sql
-- ============================================================
-- Spectre durable scheduler.
-- Run once in Supabase SQL Editor. Safe to rerun.

create table if not exists scheduled_jobs (
  id                uuid primary key default gen_random_uuid(),
  name              text not null,
  description       text,
  enabled           boolean not null default true,
  schedule_type     text not null check (schedule_type in ('once', 'interval', 'daily')),
  interval_seconds  integer,
  run_at            timestamptz,
  time_of_day       text,
  timezone          text not null default 'UTC',
  target_type       text not null check (target_type in ('chat', 'workshop', 'notify')),
  prompt            text not null,
  model_hint        text,
  thread_id         uuid references threads(id) on delete set null,
  status            text not null default 'idle' check (status in ('idle', 'running', 'failed', 'paused')),
  last_run_at       timestamptz,
  next_run_at       timestamptz,
  last_error        text,
  locked_at         timestamptz,
  locked_by         text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create table if not exists scheduled_job_runs (
  id            uuid primary key default gen_random_uuid(),
  job_id        uuid not null references scheduled_jobs(id) on delete cascade,
  status        text not null default 'running' check (status in ('running', 'completed', 'failed', 'cancelled')),
  started_at    timestamptz not null default now(),
  completed_at  timestamptz,
  output        text,
  error         text,
  thread_id     uuid references threads(id) on delete set null,
  metadata      jsonb not null default '{}'
);

create index if not exists idx_scheduled_jobs_due
  on scheduled_jobs(enabled, next_run_at)
  where enabled = true;

create index if not exists idx_scheduled_job_runs_job
  on scheduled_job_runs(job_id, started_at desc);

create or replace function touch_scheduled_jobs_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists scheduled_jobs_updated_at on scheduled_jobs;
DROP TRIGGER IF EXISTS scheduled_jobs_updated_at ON scheduled_jobs;
CREATE TRIGGER scheduled_jobs_updated_at
  before update on scheduled_jobs
  for each row
  execute function touch_scheduled_jobs_updated_at();

-- ============================================================
-- scheduled_jobs_routines.sql
-- ============================================================
-- Tempus "Routines" — adds push-on-done to the durable scheduler.
-- Run once in Supabase SQL Editor. Safe to rerun.
--
-- When a `chat` job with notify_on_done = true finishes successfully, the
-- scheduler worker fires a push notification deep-linking to the thread that
-- holds the produced report. See worker/scheduler.mjs.

alter table scheduled_jobs
  add column if not exists notify_on_done boolean not null default false;

-- Per-routine persistent state list, carried across one-shot runs. The
-- scheduler injects list_items into the run prompt and parses a trailing
-- ```routine-ops``` block from the output to add/remove items. list_kind is a
-- free label (blacklist | whitelist | notes | reminders | todos | ...) that
-- only changes the wording of the injected instructions. See
-- worker/routine-list.mjs.
alter table scheduled_jobs
  add column if not exists list_kind text,
  add column if not exists list_items jsonb not null default '[]';

-- ============================================================
-- skillopt.sql
-- ============================================================
-- SkillOpt — the optimization-round LEDGER (Step 4).
-- Run once in Supabase SQL Editor. Safe to rerun (idempotent).
--
-- One row per offline optimization ROUND for a skill: the train score, the
-- validation-gate decision (incumbent vs candidate val scores + delta), whether
-- the candidate was ACCEPTED, how many edits were applied, the held-out test
-- score of the champion, and a metadata blob carrying the proposed edits + a
-- line diff so a round can be eyeballed after the fact.
--
-- This is a DRY-RUN ledger: accepting a candidate writes skill_vN.md +
-- best_skill.md on disk (both gitignored) — it NEVER touches the live
-- skills/<skill>/SKILL.md. That deploy is Step 6, behind the workshop gate, and
-- is what `workshop_task_id` will eventually link to.
--
-- RLS idiom mirrors supabase/notes.sql exactly: service role full access, anon
-- none (this is personal optimization history).

create table if not exists skillopt_runs (
  id                    uuid primary key default gen_random_uuid(),
  skill_name            text not null,
  parent_version        text,
  new_version           text,
  train_score           float,
  incumbent_val_score   float,
  candidate_val_score   float,
  val_delta             float,
  accepted              boolean not null default false,
  edit_count            int,
  test_score            float,
  workshop_task_id      uuid,
  metadata              jsonb,
  created_at            timestamptz not null default now()
);

create index if not exists idx_skillopt_runs_skill_created
  on skillopt_runs (skill_name, created_at desc);

-- Service role full access; anon none (optimization history is personal).
alter table skillopt_runs enable row level security;

drop policy if exists "service role full access" on skillopt_runs;
DROP POLICY IF EXISTS "service role full access" ON skillopt_runs;
CREATE POLICY "service role full access" ON skillopt_runs
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- ============================================================
-- skillopt-deploy.sql
-- ============================================================
-- SkillOpt — Step 6: the APPROVAL-GATED DEPLOY column.
-- Run once in Supabase SQL Editor. Safe to rerun (idempotent).
--
-- Adds `deploy_status` to the skillopt_runs ledger (supabase/skillopt.sql).
--
-- The whole point of Step 6: an ACCEPTED candidate (val-gate passed) becomes a
-- PENDING deploy — it does NOT auto-promote to the live skills/<skill>/SKILL.md.
-- Only an EXPLICIT human approve action copies the gitignored candidate
-- (skillopt/envs/<skill>/skill_v<N>.md) onto the live doc.
--
--   deploy_status NULL        → not a deploy candidate (a rejected round)
--   deploy_status 'pending'   → accepted, awaiting human approval (no live write)
--   deploy_status 'approved'  → human approved; the live SKILL.md WAS written
--   deploy_status 'discarded' → human discarded; the live SKILL.md untouched
--
-- `deployed_at` is stamped when (and only when) a deploy is approved.
--
-- RLS stays exactly as skillopt.sql left it (service role full access, anon
-- none) — adding a column does not change the policy, so nothing to redo here.

alter table skillopt_runs
  add column if not exists deploy_status text;

alter table skillopt_runs
  add column if not exists deployed_at timestamptz;

-- Constrain the allowed values (NULL allowed = not a deploy candidate).
-- drop-then-add so a rerun re-applies the latest definition cleanly.
alter table skillopt_runs
  drop constraint if exists skillopt_runs_deploy_status_check;
alter table skillopt_runs
  add constraint skillopt_runs_deploy_status_check
  check (deploy_status is null or deploy_status in ('pending', 'approved', 'discarded'));

-- Pending deploys are read on every approval-gate poll (listPendingDeploys()).
create index if not exists idx_skillopt_runs_deploy_pending
  on skillopt_runs (created_at desc)
  where deploy_status = 'pending';

-- ============================================================
-- tempus-native.sql
-- ============================================================
-- supabase/tempus-native.sql
-- Native Tempus tables in Spectre's Supabase. Prefixed `tempus_` to
-- avoid collision with anything else in the schema. Safe to rerun.

create table if not exists tempus_projects (
  id           text primary key,
  name         text not null,
  color        text not null default '#6366f1',
  icon         text default 'folder',
  description  text default '',
  is_archived  boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists tempus_time_entries (
  id           text primary key,
  project_id   text not null references tempus_projects(id) on delete cascade,
  description  text default '',
  start_time   timestamptz not null,
  end_time     timestamptz,
  duration_ms  bigint,
  source       text not null default 'manual',
  tags         jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Single-row table -- id is always 1.
create table if not exists tempus_active_timer (
  id           int primary key default 1 check (id = 1),
  project_id   text not null references tempus_projects(id),
  start_time   timestamptz not null,
  pause_start  timestamptz,
  paused_ms    bigint not null default 0,
  description  text default ''
);

create index if not exists tempus_time_entries_project_idx on tempus_time_entries(project_id);
create index if not exists tempus_time_entries_start_idx on tempus_time_entries(start_time desc);
create index if not exists tempus_projects_archived_idx on tempus_projects(is_archived) where is_archived = false;

-- ============================================================
-- tool_policies.sql
-- ============================================================
-- Persistent tool-permission policies + a call log (quotas/audit).
-- Today the permission broker is module-level in-memory: a core restart cancels
-- every in-flight approval and `allow_session` doesn't survive. These tables let
-- a decision PERSIST (auto-resolve without re-prompting) and bound autonomous
-- tool use with optional per-tool hourly quotas. Safe to rerun.

create table if not exists tool_policies (
  id          uuid primary key default gen_random_uuid(),
  tool        text not null,                       -- e.g. mcp__spectre__bash
  scope       text not null default 'global'
              check (scope in ('global','thread','module')),
  scope_id    text,                                -- thread_id / module id; null = global
  decision    text not null check (decision in ('always_allow','always_deny')),
  quota_per_hour int,                              -- null = unlimited
  expires_at  timestamptz,                         -- null = no expiry (allow_session sets a TTL)
  created_at  timestamptz not null default now()
);

-- One live policy per (tool, scope, scope_id); a new decision replaces the old.
create unique index if not exists uq_tool_policies_target
  on tool_policies (tool, scope, coalesce(scope_id, ''));
create index if not exists idx_tool_policies_lookup
  on tool_policies (tool, scope, scope_id);

-- Audit + quota source: one row per resolved gated tool call.
create table if not exists tool_calls (
  id          uuid primary key default gen_random_uuid(),
  tool        text not null,
  thread_id   text,
  decision    text not null,                       -- 'allow' | 'deny'
  auto        boolean not null default false,      -- resolved by a policy (no prompt)
  created_at  timestamptz not null default now()
);
create index if not exists idx_tool_calls_tool_time on tool_calls (tool, created_at desc);

-- ============================================================
-- workshop-realtime.sql
-- ============================================================
-- Realtime for the workshop worker: it subscribes to workshop_tasks UPDATEs
-- (status -> pending picks up a task; status -> cancelled kills the run).
-- replica identity full so UPDATE payloads carry the row. Safe to rerun.
alter table workshop_tasks replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'workshop_tasks'
  ) then
    alter publication supabase_realtime add table workshop_tasks;
  end if;
end $$;

-- ============================================================
-- dream-default-schedule.sql
-- ============================================================
-- Nightly maintenance schedule (the scheduler's 'dream' target).
-- Run once in Supabase SQL Editor. Safe to rerun.
--
-- POST /api/dream/nightly runs memory consolidation (backfill + dedupe/merge +
-- decay) and a system health sweep (providers + storage -> debugging engine).
-- Dispatch is handled by worker/scheduler.mjs when target_type = 'dream'.
-- (Continuous learning happens per-turn via learnFromExchange, so the old
-- batch thread-distill /api/dream/run was removed.)

-- 1. Allow target_type = 'dream' on scheduled_jobs.
alter table scheduled_jobs drop constraint if exists scheduled_jobs_target_type_check;
alter table scheduled_jobs add constraint scheduled_jobs_target_type_check
  check (target_type in ('chat', 'workshop', 'notify', 'dream', 'proactive', 'skillopt', 'skill_curation'));

-- 2. Insert the daily 03:30 dream schedule if no row exists yet.
insert into scheduled_jobs (
  name,
  description,
  enabled,
  schedule_type,
  time_of_day,
  timezone,
  target_type,
  prompt,
  next_run_at
)
select
  'dream-mode',
  'Nightly maintenance — memory consolidation (dedupe/decay) + system health sweep.',
  true,
  'daily',
  '03:30',
  'UTC',
  'dream',
  'POST /api/dream/nightly',
  case
    when now() < date_trunc('day', now()) + interval '3 hours 30 minutes'
      then date_trunc('day', now()) + interval '3 hours 30 minutes'
    else date_trunc('day', now()) + interval '1 day 3 hours 30 minutes'
  end
where not exists (
  select 1 from scheduled_jobs
  where name = 'dream-mode' and target_type = 'dream'
);

-- ============================================================
-- proactive-default-schedule.sql
-- ============================================================
-- Bounded proactive run (the scheduler's 'proactive' target) — P1.1.
-- Run once in Supabase SQL Editor. Safe to rerun.
--
-- POST /api/proactive/bounded-run spawns Spectre's proactive brain with a SAFE,
-- read-mostly MCP tool whitelist (memory read/write, push notify, schedule /
-- calendar / analytics READ) under a wall-clock + per-tool hourly quota budget.
-- It pre-seeds short-TTL always_allow tool_policies so whitelisted calls
-- auto-resolve, captures the run to monitor_events, and degrades to the
-- proposal-only heartbeat if the tool_policies table isn't applied yet.
-- Dispatch is handled by worker/scheduler.mjs when target_type = 'proactive'.
--
-- Depends on supabase/tool_policies.sql (P1.2) for full tool-using behaviour;
-- without it the run still works but degrades to proposal-only.

-- 1. Allow target_type = 'proactive' on scheduled_jobs (keep prior targets).
alter table scheduled_jobs drop constraint if exists scheduled_jobs_target_type_check;
alter table scheduled_jobs add constraint scheduled_jobs_target_type_check
  check (target_type in ('chat', 'workshop', 'notify', 'dream', 'proactive', 'skillopt', 'skill_curation'));

-- 2. Insert a 4-hourly proactive schedule if no row exists yet (matches the
--    legacy heartbeat cadence). Disabled by default — flip enabled=true once
--    tool_policies.sql is applied and you want the brain acting on its own.
insert into scheduled_jobs (
  name,
  description,
  enabled,
  schedule_type,
  interval_seconds,
  timezone,
  target_type,
  prompt,
  next_run_at
)
select
  'proactive-run',
  'Bounded proactive turn — Spectre acts on its own with a safe tool whitelist (memory/notify/read-only) under a wall-clock + quota budget.',
  false,
  'interval',
  14400,
  'UTC',
  'proactive',
  'POST /api/proactive/bounded-run',
  now() + interval '4 hours'
where not exists (
  select 1 from scheduled_jobs
  where name = 'proactive-run' and target_type = 'proactive'
);

-- ============================================================
-- skillopt-schedule.sql
-- ============================================================
-- SkillOpt run schedule (the scheduler's 'skillopt' target) — Step 5.
-- Run once in Supabase SQL Editor. Safe to rerun (idempotent).
--
-- POST /api/skillopt/run drives ONE bounded offline optimization round for the
-- configured skill (rollout incumbent on train -> score -> OPUS proposes edits ->
-- budget -> apply -> VALIDATION GATE on val -> evaluate champion on test) and
-- ledgers the result to skillopt_runs. It is a DRY-RUN: accepting a candidate
-- writes skill_vN.md + best_skill.md on disk (both gitignored) — it NEVER touches
-- the live skills/<skill>/SKILL.md. That workshop-gated deploy is Step 6.
-- Dispatch is handled by worker/scheduler.mjs when target_type = 'skillopt'.
--
-- Depends on supabase/skillopt.sql (the skillopt_runs ledger, Step 4).

-- 1. Allow target_type = 'skillopt' on scheduled_jobs (keep prior targets).
alter table scheduled_jobs drop constraint if exists scheduled_jobs_target_type_check;
alter table scheduled_jobs add constraint scheduled_jobs_target_type_check
  check (target_type in ('chat', 'workshop', 'notify', 'dream', 'proactive', 'skillopt', 'skill_curation'));

-- 2. Insert a weekly off-hours SkillOpt schedule if no row exists yet.
--    DISABLED by default — flip enabled=true once you want the optimizer to run
--    offline rounds on its own. The cadence (~weekly, 604800s) runs well after
--    the nightly dream pass so the two never contend for the model. The skill to
--    optimize is carried in the prompt field (default 'memory'); the run endpoint
--    parses it from there. interval_seconds is used because the schema's
--    schedule_type CHECK is ('once','interval','daily') — there is no 'weekly',
--    so a 7-day interval is the schema-compatible way to express ~weekly.
insert into scheduled_jobs (
  name,
  description,
  enabled,
  schedule_type,
  interval_seconds,
  timezone,
  target_type,
  prompt,
  next_run_at
)
select
  'skillopt-run',
  'Weekly bounded SkillOpt optimization round for the configured skill (rollout -> reflect -> val-gate -> test). DRY-RUN: ledgers to skillopt_runs, never writes the live SKILL.md. Disabled by default.',
  false,
  'interval',
  604800,
  'UTC',
  'skillopt',
  'memory',
  now() + interval '7 days'
where not exists (
  select 1 from scheduled_jobs
  where name = 'skillopt-run' and target_type = 'skillopt'
);

-- ============================================================
-- skill-usage.sql
-- ============================================================
-- Skill-usage telemetry + the weekly curation proposal schedule.
-- Run once in Supabase SQL Editor. Safe to rerun.
--
-- The broker's skill.read tool logs a row per on-demand skill load (progressive
-- skill loading); POST /api/skills/curate reads 14-day counts + the skill index
-- and PROPOSES keep/merge/prune. Proposal-only — the SkillOpt human gate
-- applies; nothing is ever auto-deleted. Dispatch: worker/scheduler.mjs when
-- target_type = 'skill_curation'.

create table if not exists skill_usage (
  id         uuid primary key default gen_random_uuid(),
  skill      text not null,
  thread_id  text,
  created_at timestamptz not null default now()
);

create index if not exists skill_usage_skill_created_idx
  on skill_usage (skill, created_at desc);

-- 1. Allow target_type = 'skill_curation' (cumulative enum — keep this file
--    LAST among the schedule files in scripts/gen-apply-all.mjs ORDER).
alter table scheduled_jobs drop constraint if exists scheduled_jobs_target_type_check;
alter table scheduled_jobs add constraint scheduled_jobs_target_type_check
  check (target_type in ('chat', 'workshop', 'notify', 'dream', 'proactive', 'skillopt', 'skill_curation'));

-- 2. Seed the weekly curation job if no row exists yet.
insert into scheduled_jobs (
  name, description, enabled, schedule_type, interval_seconds,
  target_type, prompt, next_run_at
)
select
  'skill-curation',
  'Weekly skill-library review — 14d usage + redundancy; proposes keep/merge/prune, never deletes.',
  true,
  'interval',
  604800,
  'skill_curation',
  'POST /api/skills/curate',
  now() + interval '7 days'
where not exists (
  select 1 from scheduled_jobs
  where name = 'skill-curation' and target_type = 'skill_curation'
);
