/**
 * Rotating spinner verbs — cycle through while a response is streaming.
 * Inspired by the Claude Code leak ("187 distinct variations for status
 * messaging"). We keep it tasteful: no emoji, no ad-speak, no drama.
 */
export const SPINNER_VERBS = [
  "Thinking",
  "Cogitating",
  "Pondering",
  "Considering",
  "Weighing",
  "Tracing",
  "Untangling",
  "Parsing",
  "Mulling",
  "Reflecting",
  "Sifting",
  "Correlating",
  "Distilling",
  "Cross-referencing",
  "Dissecting",
  "Scrutinizing",
  "Inspecting",
  "Examining",
  "Surveying",
  "Reasoning",
  "Deliberating",
  "Contemplating",
  "Calculating",
  "Formulating",
  "Drafting",
  "Composing",
  "Assembling",
  "Collating",
  "Synthesizing",
  "Recollecting",
  "Recalling",
  "Querying",
  "Probing",
  "Manifesting",
  "Conjuring",
  "Materializing",
  "Orchestrating",
  "Marshalling",
  "Rummaging",
  "Burrowing",
  "Spelunking",
  "Diving",
  "Squinting",
  "Scheming",
  "Plotting",
  "Planning",
  "Reviewing",
  "Revising",
  "Polishing",
  "Sharpening",
  "Sculpting",
  "Stitching",
  "Weaving",
  "Kneading",
  "Percolating",
  "Steeping",
  "Brewing",
  "Simmering",
  "Compiling",
  "Mapping",
  "Tallying",
  "Reckoning",
  "Noodling",
  "Puzzling",
  "Untying",
  "Deciphering",
  "Decoding",
  "Wrangling",
  "Herding",
  "Rallying",
] as const;

/** Pick a verb that stays stable for ~2 seconds at a time. */
export function verbForTick(tick: number): string {
  return SPINNER_VERBS[tick % SPINNER_VERBS.length];
}
